In [ ]:
!pip install regex

In [ ]:
!pip install selenium

In [ ]:
!pip install sqlite3

In [ ]:
!pip install json

In [1]:
import sqlite3
import numpy as np
import pandas as pd
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
import requests
import time
import re

In [2]:
df = pd.DataFrame(columns=["id","name","university","emp_rate"])

In [3]:
universities_l = ["UNAM","TEC MONTERREY"]

unam_careers = [
    # ÁREA 1
    "Ingeniería Civil",
    "Ingeniería en Computación",
    "Ingeniería Industrial",
    "Ingeniería Eléctrica",
    "Ingeniería Mecánica",

    # ÁREA 2
    "Médico Cirujano",
    "Psicología",
    "Biología",
    "Ingeniería Química",

    # ÁREA 3
    "Derecho",
    "Administración",
    "Economía",
    "Comunicación",

    # ÁREA 4
    "Arquitectura",
    "Diseño Gráfico",
    "Urbanismo",
    "Historia",
]

tec_careers = [
    # ÁREA 1
    "Ingeniería Civil",
    "Ingeniería en Tecnologías Computacionales",
    "Ingeniería Industrial y de Sistemas",
    "Ingeniería en Electrónica y Semiconductores",
    "Ingeniería Mecánica",

    # ÁREA 2
    "Médico Cirujano",
    "Licenciatura en Psicología Clínica y de la Salud",
    "Licenciatura en Biociencias",
    "Ingeniería Química",

    # ÁREA 3
    "Licenciatura en Derecho",
    "Licenciatura en Estrategia y Transformación de Negocios",
    "Licenciatura en Finanzas",
    "Licenciatura en Comunicación y Producción Digital",

    # ÁREA 4
    "Licenciatura en Arquitectura",
    "Licenciatura en Diseño",
    "Licenciatura en Urbanismo",
    "Licenciatura en Humanidades Digitales e Inteligencia Artificial",
]
qs_links = {
    # ÁREA 1 – Engineering and Technology
    "Ingeniería Civil": "https://www.topuniversities.com/university-subject-rankings/civil-structural-engineering",
    "Ingeniería en Computación": "https://www.topuniversities.com/university-subject-rankings/computer-science-information-systems",
    "Ingeniería Industrial": "https://www.topuniversities.com/university-subject-rankings/mechanical-aeronautical-manufacturing-engineering",
    "Ingeniería Eléctrica": "https://www.topuniversities.com/university-subject-rankings/electrical-electronic-engineering",
    "Ingeniería Mecánica": "https://www.topuniversities.com/university-subject-rankings/mechanical-aeronautical-manufacturing-engineering",

    # ÁREA 2 – Life Sciences & Medicine
    "Médico Cirujano": "https://www.topuniversities.com/university-subject-rankings/medicine",
    "Psicología": "https://www.topuniversities.com/university-subject-rankings/psychology",
    "Biología": "https://www.topuniversities.com/university-subject-rankings/biological-sciences",
    "Ingeniería Química": "https://www.topuniversities.com/university-subject-rankings/chemical-engineering",

    # ÁREA 3 – Social Sciences & Management
    "Derecho": "https://www.topuniversities.com/university-subject-rankings/law-legal-studies",
    "Administración": "https://www.topuniversities.com/university-subject-rankings/business-management-studies",
    "Economía / Finanzas": "https://www.topuniversities.com/university-subject-rankings/economics-econometrics",
    "Comunicación": "https://www.topuniversities.com/university-subject-rankings/communication-media-studies",

    # ÁREA 4 – Arts & Humanities
    "Arquitectura": "https://www.topuniversities.com/university-subject-rankings/architecture-built-environment",
    "Diseño Gráfico": "https://www.topuniversities.com/university-subject-rankings/art-design",
    "Urbanismo": "https://www.topuniversities.com/university-subject-rankings/architecture-built-environment",
    "Historia": "https://www.topuniversities.com/university-subject-rankings/art-history"
}

In [4]:
def getEmployer_Reputation(university,id,array_careers,qs_links):
    filas = []
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Ejecutar en segundo plano
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    
    driver = webdriver.Chrome(options=chrome_options)
    try:
        for i in range(len(array_careers)):
            prepath = list(qs_links.values())[i]
            url = prepath + f"?search={university}"
            print(url)
            driver.get(url)
            time.sleep(5)
            page_source = driver.page_source
            if university in page_source.lower():
                elemento = driver.find_element(By.CLASS_NAME, "new-rankings-ind-val")
                emp_rate = elemento.text
                print(f"Emp rate {emp_rate}")
            else:
                emp_rate = None
                print("No se encontró el bloque de Employer Reputation.")
            filas.append({"id":i ,"name":array_careers[i], "university":id, "spe_fee":None, "emp_rate":emp_rate})
    finally:
        driver.quit()
        print("Completado")
    return filas

In [5]:
unam_filas = getEmployer_Reputation("unam",1,unam_careers,qs_links)

https://www.topuniversities.com/university-subject-rankings/civil-structural-engineering?search=unam
Emp rate 81.7
https://www.topuniversities.com/university-subject-rankings/computer-science-information-systems?search=unam
Emp rate 83
https://www.topuniversities.com/university-subject-rankings/mechanical-aeronautical-manufacturing-engineering?search=unam
Emp rate 80
https://www.topuniversities.com/university-subject-rankings/electrical-electronic-engineering?search=unam
Emp rate 74.5
https://www.topuniversities.com/university-subject-rankings/mechanical-aeronautical-manufacturing-engineering?search=unam
Emp rate 80
https://www.topuniversities.com/university-subject-rankings/medicine?search=unam
Emp rate 78.6
https://www.topuniversities.com/university-subject-rankings/psychology?search=unam
Emp rate 88.1
https://www.topuniversities.com/university-subject-rankings/biological-sciences?search=unam
Emp rate 83.6
https://www.topuniversities.com/university-subject-rankings/chemical-engineering?search=unam
Emp rate 80.5
https://www.topuniversities.com/university-subject-rankings/law-legal-studies?search=unam
Emp rate 84.2
https://www.topuniversities.com/university-subject-rankings/business-management-studies?search=unam
Emp rate 82.1
https://www.topuniversities.com/university-subject-rankings/economics-econometrics?search=unam
Emp rate 80.6
https://www.topuniversities.com/university-subject-rankings/communication-media-studies?search=unam
Emp rate 82.6
https://www.topuniversities.com/university-subject-rankings/architecture-built-environment?search=unam
Emp rate 88.7
https://www.topuniversities.com/university-subject-rankings/art-design?search=unam
Emp rate 83.5
https://www.topuniversities.com/university-subject-rankings/architecture-built-environment?search=unam
Emp rate 88.7
https://www.topuniversities.com/university-subject-rankings/art-history?search=unam
Emp rate 80.1
Completado

In [6]:
tec_filas = getEmployer_Reputation("monterrey",2,tec_careers,qs_links)

https://www.topuniversities.com/university-subject-rankings/civil-structural-engineering?search=monterrey
Emp rate 82.8
https://www.topuniversities.com/university-subject-rankings/computer-science-information-systems?search=monterrey
Emp rate 85.3
https://www.topuniversities.com/university-subject-rankings/mechanical-aeronautical-manufacturing-engineering?search=monterrey
Emp rate 81
https://www.topuniversities.com/university-subject-rankings/electrical-electronic-engineering?search=monterrey
Emp rate 77.8
https://www.topuniversities.com/university-subject-rankings/mechanical-aeronautical-manufacturing-engineering?search=monterrey
Emp rate 81
https://www.topuniversities.com/university-subject-rankings/medicine?search=monterrey
Emp rate 73.2
https://www.topuniversities.com/university-subject-rankings/psychology?search=monterrey
Emp rate 89.9
https://www.topuniversities.com/university-subject-rankings/biological-sciences?search=monterrey
Emp rate 76.5
https://www.topuniversities.com/university-subject-rankings/chemical-engineering?search=monterrey
Emp rate 75
https://www.topuniversities.com/university-subject-rankings/law-legal-studies?search=monterrey
Emp rate 84.8
https://www.topuniversities.com/university-subject-rankings/business-management-studies?search=monterrey
Emp rate 85.1
https://www.topuniversities.com/university-subject-rankings/economics-econometrics?search=monterrey
Emp rate 82.1
https://www.topuniversities.com/university-subject-rankings/communication-media-studies?search=monterrey
Emp rate 83.2
https://www.topuniversities.com/university-subject-rankings/architecture-built-environment?search=monterrey
Emp rate 88.3
https://www.topuniversities.com/university-subject-rankings/art-design?search=monterrey
Emp rate 86.8
https://www.topuniversities.com/university-subject-rankings/architecture-built-environment?search=monterrey
Emp rate 88.3
https://www.topuniversities.com/university-subject-rankings/art-history?search=monterrey
Emp rate 89.4
Completado

In [7]:
df = pd.concat([df, pd.DataFrame(unam_filas, columns=df.columns)], ignore_index=False)
df = pd.concat([df, pd.DataFrame(tec_filas, columns=df.columns)], ignore_index=False)

In [8]:
careers = [
    "construcción_e_ingeniería_civil",
    "ciencias_computacionales",
    "ingeniería_industrial",
    "electrónica_automatización_y_aplicaciones_de_la_mecánica-eléctrica",
    "mecánica_y_profesiones_afines_al_trabajo_metálico",
    
    "medicina_general",
    "psicología",
    "biología",
    "ingeniería_de_procesos_químicos",
    
    "derecho",
    "administración_de_empresas",
    "economía",
    "comunicación_y_periodismo",
    
    "arquitectura_y_urbanismo",
    "diseño_y_comunicación_gráfica_y_editorial",
    "arquitectura_y_urbanismo",
    "historia_y_arqueología",
]

In [24]:
def getStatistics(careers):
    filas = []
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # Ejecutar en segundo plano
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    
    driver = webdriver.Chrome(options=chrome_options)
    
    try:
        for i in range(len(careers)):
            url = f"https://comparacarreras.imco.org.mx/{careers[i]}"
            print(url)
            driver.get(url)
            time.sleep(5)
            page_source = driver.page_source
            total_students = driver.find_element(By.XPATH, '//*[@id="total-students"]/h3').text
            new_graduates_number = driver.find_element(By.ID, "new-graduates-number").text
            
            public_cost = driver.find_element(By.ID, "public-cost").text
            private_cost = driver.find_element(By.ID, "private-cost").text
            public_quality_rating = driver.find_element(By.ID, "public-quality-rating").text
            private_quality_rating = driver.find_element(By.ID, "private-quality-rating").text

            occupation_rate = driver.find_element(By.ID, "occupation-rate").text
            unemployment_rate = driver.find_element(By.ID, "unemployment-rate").text
            informality_rate = driver.find_element(By.ID, "informality-rate").text
            quality_employment_probability = driver.find_element(By.ID, "quality-employment-probability").text

            average_salary = driver.find_element(By.ID, "average-salary").text
            career_rank = driver.find_element(By.ID, "career-rank").text

            women_salary = driver.find_element(By.ID, "women-salary").text
            men_salary = driver.find_element(By.ID, "men-salary").text
            under_30_salary = driver.find_element(By.ID, "under-30-salary").text
            over_30_salary = driver.find_element(By.ID, "over-30-salary").text
            formal_salary = driver.find_element(By.ID, "formal-salary").text
            informal_salary = driver.find_element(By.ID, "informal-salary").text

            postgrad_percentage = driver.find_element(By.ID, "postgrad-percentage").text
            postgrad_salary = driver.find_element(By.ID, "postgrad-salary").text
            salary_increase = driver.find_element(By.ID, "salary-increase").text

            filas.append({
                "id":i,
                "career": careers[i],
                "total_students":total_students,
                "new_graduates_number":new_graduates_number,
                "public_cost": public_cost,
                "private_cost": private_cost,
                "public_quality_rating": public_quality_rating,
                "private_quality_rating": private_quality_rating,
                "occupation_rate": occupation_rate,
                "unemployment_rate": unemployment_rate,
                "informality_rate": informality_rate,
                "quality_employment_probability": quality_employment_probability,
                "average_salary": average_salary,
                "career_rank": career_rank,
                "women_salary": women_salary,
                "men_salary": men_salary,
                "under_30_salary": under_30_salary,
                "over_30_salary": over_30_salary,
                "formal_salary": formal_salary,
                "informal_salary": informal_salary,
                "postgrad_percentage": postgrad_percentage,
                "postgrad_salary": postgrad_salary,
                "salary_increase": salary_increase
            })
    finally:
        driver.quit()
        print("Completado")
    return filas

In [25]:
#<div id="public-cost" class="stat-value">$42,437</div>
#<div id="private-cost" class="stat-value">$90,757</div>
#<div id="public-quality-rating" class="quality-rating">Buena</div>
#<div id="private-quality-rating" class="quality-rating">Excelente</div>

#<div id="occupation-rate" class="employment-stat-value">96.0%</div>
#<div id="unemployment-rate" class="employment-stat-value">4.0%</div>
#<div id="informality-rate" class="employment-stat-value">25.9%</div> --

#<div id="quality-employment-probability" class="probability-value">74.0%</div>

#<h4 id="average-salary">$25,676</h4>
#<h4 id="career-rank">5°</h4> 

#<p id="women-salary">$23,723</p>
#<p id="men-salary">$26,821</p>
#<p id="under-30-salary">$17,118</p>
#<p id="over-30-salary">$28,654</p>
#<p id="formal-salary">$27,745</p>
#<p id="informal-salary">$17,327</p>

#<h4 id="postgrad-percentage">6.9%</h4>
#<h4 id="postgrad-salary">$43,574</h4>
#<h4 id="salary-increase">206.11%</h4>

In [26]:
data = getStatistics(careers)

https://comparacarreras.imco.org.mx/construcción_e_ingeniería_civil
https://comparacarreras.imco.org.mx/ciencias_computacionales
https://comparacarreras.imco.org.mx/ingeniería_industrial
https://comparacarreras.imco.org.mx/electrónica_automatización_y_aplicaciones_de_la_mecánica-eléctrica
https://comparacarreras.imco.org.mx/mecánica_y_profesiones_afines_al_trabajo_metálico
https://comparacarreras.imco.org.mx/medicina_general
https://comparacarreras.imco.org.mx/psicología
https://comparacarreras.imco.org.mx/biología
https://comparacarreras.imco.org.mx/ingeniería_de_procesos_químicos
https://comparacarreras.imco.org.mx/derecho
https://comparacarreras.imco.org.mx/administración_de_empresas
https://comparacarreras.imco.org.mx/economía
https://comparacarreras.imco.org.mx/comunicación_y_periodismo
https://comparacarreras.imco.org.mx/arquitectura_y_urbanismo
https://comparacarreras.imco.org.mx/diseño_y_comunicación_gráfica_y_editorial
https://comparacarreras.imco.org.mx/arquitectura_y_urbanismo
https://comparacarreras.imco.org.mx/historia_y_arqueología
Completado

In [27]:
df_data = pd.json_normalize(data)

In [28]:
df_data

,id,career,total_students,new_graduates_number,public_cost,private_cost,public_quality_rating,private_quality_rating,occupation_rate,unemployment_rate,...,career_rank,women_salary,men_salary,under_30_salary,over_30_salary,formal_salary,informal_salary,postgrad_percentage,postgrad_salary,salary_increase
0,0,construcción_e_ingeniería_civil,337.269,10.559,$47.375,$248.283,Insegura,Buena,96.2%,3.8%,...,7°,$24.108,$25.518,$21.204,$26.826,$27.119,$18.928,3.9%,$41.396,"191,62%"
1,1,ciencias_computacionales,109.896,990,$42.437,$90.757,Buena,Excelente,96.0%,4.0%,...,5°,$23.723,$26.821,$17.118,$28.654,$27.745,$17.327,6.9%,$43.574,"206,11%"
2,2,ingeniería_industrial,601.331,40.232,$49.736,$393.684,Excelente,Buena,96.5%,3.5%,...,15°,$19.942,$24.854,$20.188,$25.369,$25.109,$14.568,3.2%,$43.391,"214,62%"
3,3,electrónica_automatización_y_aplicaciones_de_l...,408.206,24.702,$54.886,$496.800,Excelente,Buena,96.3%,3.7%,...,4°,$21.431,$26.108,$21.596,$28.051,$27.429,$15.484,1.9%,$41.086,"185,06%"
4,4,mecánica_y_profesiones_afines_al_trabajo_metálico,205.424,11.478,$51.344,$1.2M,Excelente,Insegura,97.4%,2.6%,...,11°,$29.237,$23.165,$22.696,$24.811,$25.981,$14.836,1.2%,$42.794,"206,03%"
5,5,medicina_general,292.141,18.871,$70.605,$860.982,Excelente,Insegura,97.9%,2.1%,...,3°,$23.479,$28.457,$21.990,$27.437,$27.888,$17.390,-,$-,-%
6,6,psicología,595.676,31.993,$60.886,$269.914,Muy Insegura,Insegura,95.7%,4.3%,...,31°,$18.040,$19.192,$16.807,$18.994,$20.112,$12.355,9.6%,$28.302,"184,26%"
7,7,biología,110.499,4180,-,-,-,-,95.7%,4.3%,...,-°,$-,$-,$-,$-,$-,$-,14.3%,$-,-%
8,8,ingeniería_de_procesos_químicos,194.965,9542,-,-,-,-,96.1%,3.9%,...,-°,$-,$-,$-,$-,$-,$-,3.8%,$-,-%
9,9,derecho,1.3M,70.987,$52.710,$208.023,Insegura,Insegura,96.5%,3.5%,...,19°,$20.846,$23.349,$17.164,$23.697,$24.653,$15.686,8.8%,$40.639,"222,62%"
10,10,administración_de_empresas,1.3M,47.537,$50.156,$228.756,Buena,Buena,96.8%,3.3%,...,18°,$19.561,$25.207,$16.723,$24.358,$23.740,$16.242,8.5%,$43.317,"236,71%"
11,11,economía,144.332,4147,$44.483,$97.957,Excelente,Excelente,95.1%,4.9%,...,2°,$26.877,$31.332,$28.167,$30.065,$32.136,$15.995,12.9%,$56.013,"237,78%"
12,12,comunicación_y_periodismo,251.824,10.476,$40.929,$391.302,Insegura,Insegura,95.9%,4.1%,...,23°,$19.508,$21.967,$16.668,$21.930,$22.906,$15.417,5.5%,$34.421,"195,89%"
13,13,arquitectura_y_urbanismo,361.035,16.191,$52.066,$185.974,Insegura,Insegura,95.3%,4.7%,...,9°,$22.322,$25.730,$20.794,$26.403,$27.427,$18.037,3.7%,$36.343,"170,49%"
14,14,diseño_y_comunicación_gráfica_y_editorial,199.645,9837,-,-,-,-,94.8%,5.2%,...,-°,$-,$-,$-,$-,$-,$-,3.4%,$-,-%
15,15,arquitectura_y_urbanismo,361.035,16.191,$52.066,$185.974,Insegura,Insegura,95.3%,4.7%,...,9°,$22.322,$25.730,$20.794,$26.403,$27.427,$18.037,3.7%,$36.343,"170,49%"
16,16,historia_y_arqueología,42.289,1040,-,-,-,-,98.0%,2.0%,...,-°,$-,$-,$-,$-,$-,$-,42.2%,$-,-%

In [29]:
df

    id                                               name university emp_rate
0    0                                   Ingeniería Civil          1     81.7
1    1                          Ingeniería en Computación          1       83
2    2                              Ingeniería Industrial          1       80
3    3                               Ingeniería Eléctrica          1     74.5
4    4                                Ingeniería Mecánica          1       80
5    5                                    Médico Cirujano          1     78.6
6    6                                         Psicología          1     88.1
7    7                                           Biología          1     83.6
8    8                                 Ingeniería Química          1     80.5
9    9                                            Derecho          1     84.2
10  10                                     Administración          1     82.1
11  11                                           Economía          1     80.6
12  12                                       Comunicación          1     82.6
13  13                                       Arquitectura          1     88.7
14  14                                     Diseño Gráfico          1     83.5
15  15                                          Urbanismo          1     88.7
16  16                                           Historia          1     80.1
0    0                                   Ingeniería Civil          2     82.8
1    1          Ingeniería en Tecnologías Computacionales          2     85.3
2    2                Ingeniería Industrial y de Sistemas          2       81
3    3        Ingeniería en Electrónica y Semiconductores          2     77.8
4    4                                Ingeniería Mecánica          2       81
5    5                                    Médico Cirujano          2     73.2
6    6   Licenciatura en Psicología Clínica y de la Salud          2     89.9
7    7                        Licenciatura en Biociencias          2     76.5
8    8                                 Ingeniería Química          2       75
9    9                            Licenciatura en Derecho          2     84.8
10  10  Licenciatura en Estrategia y Transformación de...          2     85.1
11  11                           Licenciatura en Finanzas          2     82.1
12  12  Licenciatura en Comunicación y Producción Digital          2     83.2
13  13                       Licenciatura en Arquitectura          2     88.3
14  14                             Licenciatura en Diseño          2     86.8
15  15                          Licenciatura en Urbanismo          2     88.3
16  16  Licenciatura en Humanidades Digitales e Inteli...          2     89.4

In [30]:
result = pd.merge(df, df_data, on="id")

In [31]:
result

,id,name,university,emp_rate,career,total_students,new_graduates_number,public_cost,private_cost,public_quality_rating,...,career_rank,women_salary,men_salary,under_30_salary,over_30_salary,formal_salary,informal_salary,postgrad_percentage,postgrad_salary,salary_increase
0,0,Ingeniería Civil,1,81.7,construcción_e_ingeniería_civil,337.269,10.559,$47.375,$248.283,Insegura,...,7°,$24.108,$25.518,$21.204,$26.826,$27.119,$18.928,3.9%,$41.396,"191,62%"
1,0,Ingeniería Civil,2,82.8,construcción_e_ingeniería_civil,337.269,10.559,$47.375,$248.283,Insegura,...,7°,$24.108,$25.518,$21.204,$26.826,$27.119,$18.928,3.9%,$41.396,"191,62%"
2,1,Ingeniería en Computación,1,83,ciencias_computacionales,109.896,990,$42.437,$90.757,Buena,...,5°,$23.723,$26.821,$17.118,$28.654,$27.745,$17.327,6.9%,$43.574,"206,11%"
3,1,Ingeniería en Tecnologías Computacionales,2,85.3,ciencias_computacionales,109.896,990,$42.437,$90.757,Buena,...,5°,$23.723,$26.821,$17.118,$28.654,$27.745,$17.327,6.9%,$43.574,"206,11%"
4,2,Ingeniería Industrial,1,80,ingeniería_industrial,601.331,40.232,$49.736,$393.684,Excelente,...,15°,$19.942,$24.854,$20.188,$25.369,$25.109,$14.568,3.2%,$43.391,"214,62%"
5,2,Ingeniería Industrial y de Sistemas,2,81,ingeniería_industrial,601.331,40.232,$49.736,$393.684,Excelente,...,15°,$19.942,$24.854,$20.188,$25.369,$25.109,$14.568,3.2%,$43.391,"214,62%"
6,3,Ingeniería Eléctrica,1,74.5,electrónica_automatización_y_aplicaciones_de_l...,408.206,24.702,$54.886,$496.800,Excelente,...,4°,$21.431,$26.108,$21.596,$28.051,$27.429,$15.484,1.9%,$41.086,"185,06%"
7,3,Ingeniería en Electrónica y Semiconductores,2,77.8,electrónica_automatización_y_aplicaciones_de_l...,408.206,24.702,$54.886,$496.800,Excelente,...,4°,$21.431,$26.108,$21.596,$28.051,$27.429,$15.484,1.9%,$41.086,"185,06%"
8,4,Ingeniería Mecánica,1,80,mecánica_y_profesiones_afines_al_trabajo_metálico,205.424,11.478,$51.344,$1.2M,Excelente,...,11°,$29.237,$23.165,$22.696,$24.811,$25.981,$14.836,1.2%,$42.794,"206,03%"
9,4,Ingeniería Mecánica,2,81,mecánica_y_profesiones_afines_al_trabajo_metálico,205.424,11.478,$51.344,$1.2M,Excelente,...,11°,$29.237,$23.165,$22.696,$24.811,$25.981,$14.836,1.2%,$42.794,"206,03%"
10,5,Médico Cirujano,1,78.6,medicina_general,292.141,18.871,$70.605,$860.982,Excelente,...,3°,$23.479,$28.457,$21.990,$27.437,$27.888,$17.390,-,$-,-%
11,5,Médico Cirujano,2,73.2,medicina_general,292.141,18.871,$70.605,$860.982,Excelente,...,3°,$23.479,$28.457,$21.990,$27.437,$27.888,$17.390,-,$-,-%
12,6,Psicología,1,88.1,psicología,595.676,31.993,$60.886,$269.914,Muy Insegura,...,31°,$18.040,$19.192,$16.807,$18.994,$20.112,$12.355,9.6%,$28.302,"184,26%"
13,6,Licenciatura en Psicología Clínica y de la Salud,2,89.9,psicología,595.676,31.993,$60.886,$269.914,Muy Insegura,...,31°,$18.040,$19.192,$16.807,$18.994,$20.112,$12.355,9.6%,$28.302,"184,26%"
14,7,Biología,1,83.6,biología,110.499,4180,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,14.3%,$-,-%
15,7,Licenciatura en Biociencias,2,76.5,biología,110.499,4180,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,14.3%,$-,-%
16,8,Ingeniería Química,1,80.5,ingeniería_de_procesos_químicos,194.965,9542,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,3.8%,$-,-%
17,8,Ingeniería Química,2,75,ingeniería_de_procesos_químicos,194.965,9542,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,3.8%,$-,-%
18,9,Derecho,1,84.2,derecho,1.3M,70.987,$52.710,$208.023,Insegura,...,19°,$20.846,$23.349,$17.164,$23.697,$24.653,$15.686,8.8%,$40.639,"222,62%"
19,9,Licenciatura en Derecho,2,84.8,derecho,1.3M,70.987,$52.710,$208.023,Insegura,...,19°,$20.846,$23.349,$17.164,$23.697,$24.653,$15.686,8.8%,$40.639,"222,62%"
20,10,Administración,1,82.1,administración_de_empresas,1.3M,47.537,$50.156,$228.756,Buena,...,18°,$19.561,$25.207,$16.723,$24.358,$23.740,$16.242,8.5%,$43.317,"236,71%"
21,10,Licenciatura en Estrategia y Transformación de...,2,85.1,administración_de_empresas,1.3M,47.537,$50.156,$228.756,Buena,...,18°,$19.561,$25.207,$16.723,$24.358,$23.740,$16.242,8.5%,$43.317,"236,71%"
22,11,Economía,1,80.6,economía,144.332,4147,$44.483,$97.957,Excelente,...,2°,$26.877,$31.332,$28.167,$30.065,$32.136,$15.995,12.9%,$56.013,"237,78%"
23,11,Licenciatura en Finanzas,2,82.1,economía,144.332,4147,$44.483,$97.957,Excelente,...,2°,$26.877,$31.332,$28.167,$30.065,$32.136,$15.995,12.9%,$56.013,"237,78%"
24,12,Comunicación,1,82.6,comunicación_y_periodismo,251.824,10.476,$40.929,$391.302,Insegura,...,23°,$19.508,$21.967,$16.668,$21.930,$22.906,$15.417,5.5%,$34.421,"195,89%"
25,12,Licenciatura en Comunicación y Producción Digital,2,83.2,comunicación_y_periodismo,251.824,10.476,$40.929,$391.302,Insegura,...,23°,$19.508,$21.967,$16.668,$21.930,$22.906,$15.417,5.5%,$34.421,"195,89%"
26,13,Arquitectura,1,88.7,arquitectura_y_urbanismo,361.035,16.191,$52.066,$185.974,Insegura,...,9°,$22.322,$25.730,$20.794,$26.403,$27.427,$18.037,3.7%,$36.343,"170,49%"
27,13,Licenciatura en Arquitectura,2,88.3,arquitectura_y_urbanismo,361.035,16.191,$52.066,$185.974,Insegura,...,9°,$22.322,$25.730,$20.794,$26.403,$27.427,$18.037,3.7%,$36.343,"170,49%"
28,14,Diseño Gráfico,1,83.5,diseño_y_comunicación_gráfica_y_editorial,199.645,9837,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,3.4%,$-,-%
29,14,Licenciatura en Diseño,2,86.8,diseño_y_comunicación_gráfica_y_editorial,199.645,9837,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,3.4%,$-,-%
30,15,Urbanismo,1,88.7,arquitectura_y_urbanismo,361.035,16.191,$52.066,$185.974,Insegura,...,9°,$22.322,$25.730,$20.794,$26.403,$27.427,$18.037,3.7%,$36.343,"170,49%"
31,15,Licenciatura en Urbanismo,2,88.3,arquitectura_y_urbanismo,361.035,16.191,$52.066,$185.974,Insegura,...,9°,$22.322,$25.730,$20.794,$26.403,$27.427,$18.037,3.7%,$36.343,"170,49%"
32,16,Historia,1,80.1,historia_y_arqueología,42.289,1040,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,42.2%,$-,-%
33,16,Licenciatura en Humanidades Digitales e Inteli...,2,89.4,historia_y_arqueología,42.289,1040,-,-,-,...,-°,$-,$-,$-,$-,$-,$-,42.2%,$-,-%

In [32]:
result.to_csv('data_avance.csv')