In [101]:
import pandas as pd
import numpy as np

In [102]:
w0 = -.8
b = -.8
w1 = 0.5
w2 = 0.5
alpha = 0.2
threshold = 0.4

In [103]:
def function_threshold(net, threshold):
    if net > threshold:
        return 1
    if net < threshold:
        return -1

In [104]:
def lab_perceptron (df,w1, w2, alpha, threshold, b = 0):
    for epoca in range(1,4):
        for iter in range(1,5):
            print(f"\nÉpoca {epoca} en la iteración {iter}")
            net = (w1 * df['x1'][iter])  + (w2 * df['x2'][iter]) + b
            print(f"net = {net:.2f} = ({w1:.2f} * {df['x1'][iter]})  + ({w2} * {df['x2'][iter]}) + {b:.2f}")
            ynet = function_threshold(net, threshold)
            print(f"Valor de ynet después de threshold:  {ynet}")
            err = ynet - (df['t'][iter])
            if ynet != df['t'][iter]:
                w1_ = w1
                w2_ = w2
                b_ = b
                w1 = w1 + (alpha * df['t'][iter] *  df['x1'][iter])
                w2 = w2 + (alpha * df['t'][iter] *  df['x2'][iter])
                b = b +  (alpha * df['t'][iter] * 1)
                print(f"w1 = {w1:.2f} = {w1_:.2f} + ({alpha} * {df['t'][iter]} *  {df['x1'][iter]})")
                print(f"w2 = {w2:.2f} = {w2_:.2f} + ({alpha} * {df['t'][iter]} *  {df['x2'][iter]})")
                print(f"b = {b:.2f} = {b_:.2f} +  ({alpha} * {df['t'][iter]} * 1)")
            else:
                print("NO UPDATE")
            if iter == 4:
                print("\nLos valores para la última iteración de la época ",epoca," son:")
                print(f"bias: {b:.2f}")
                print(f"w1:  {w1:.2f}")
                print(f"w2: {w2:.2f}")

In [105]:
df_or = pd.DataFrame(np.array([[0, 0, -1], [0, 1, 1], [1, 0, 1], [1, 1, 1]]),
                   columns=['x1', 'x2', 't'], 
                  index=[1, 2, 3, 4])
df_or

   x1  x2  t
1   0   0 -1
2   0   1  1
3   1   0  1
4   1   1  1

In [106]:
w0 = -.8
b = -.8
w1 = 0.5
w2 = 0.5
alpha = 0.2
threshold = 0.4
lab_perceptron(df_or,w1, w2, alpha, threshold, b)

Época 1 en la iteración 1
net = -0.80 = (0.50 * 0)  + (0.5 * 0) + -0.80
Valor de ynet después de threshold:  -1
NO UPDATE

Época 1 en la iteración 2
net = -0.30 = (0.50 * 0)  + (0.5 * 1) + -0.80
Valor de ynet después de threshold:  -1
w1 = 0.50 = 0.50 + (0.2 * 1 *  0)
w2 = 0.70 = 0.50 + (0.2 * 1 *  1)
b = -0.60 = -0.80 +  (0.2 * 1 * 1)

Época 1 en la iteración 3
net = -0.10 = (0.50 * 1)  + (0.7 * 0) + -0.60
Valor de ynet después de threshold:  -1
w1 = 0.70 = 0.50 + (0.2 * 1 *  1)
w2 = 0.70 = 0.70 + (0.2 * 1 *  0)
b = -0.40 = -0.60 +  (0.2 * 1 * 1)

Época 1 en la iteración 4
net = 1.00 = (0.70 * 1)  + (0.7 * 1) + -0.40
Valor de ynet después de threshold:  1
NO UPDATE

Los valores para la última iteración de la época  1  son:
bias: -0.40
w1:  0.70
w2: 0.70

Época 2 en la iteración 1
net = -0.40 = (0.70 * 0)  + (0.7 * 0) + -0.40
Valor de ynet después de threshold:  -1
NO UPDATE

Época 2 en la iteración 2
net = 0.30 = (0.70 * 0)  + (0.7 * 1) + -0.40
Valor de ynet después de threshold:  -1
w1 = 0.70 = 0.70 + (0.2 * 1 *  0)
w2 = 0.90 = 0.70 + (0.2 * 1 *  1)
b = -0.20 = -0.40 +  (0.2 * 1 * 1)

Época 2 en la iteración 3
net = 0.50 = (0.70 * 1)  + (0.8999999999999999 * 0) + -0.20
Valor de ynet después de threshold:  1
NO UPDATE

Época 2 en la iteración 4
net = 1.40 = (0.70 * 1)  + (0.8999999999999999 * 1) + -0.20
Valor de ynet después de threshold:  1
NO UPDATE

Los valores para la última iteración de la época  2  son:
bias: -0.20
w1:  0.70
w2: 0.90

Época 3 en la iteración 1
net = -0.20 = (0.70 * 0)  + (0.8999999999999999 * 0) + -0.20
Valor de ynet después de threshold:  -1
NO UPDATE

Época 3 en la iteración 2
net = 0.70 = (0.70 * 0)  + (0.8999999999999999 * 1) + -0.20
Valor de ynet después de threshold:  1
NO UPDATE

Época 3 en la iteración 3
net = 0.50 = (0.70 * 1)  + (0.8999999999999999 * 0) + -0.20
Valor de ynet después de threshold:  1
NO UPDATE

Época 3 en la iteración 4
net = 1.40 = (0.70 * 1)  + (0.8999999999999999 * 1) + -0.20
Valor de ynet después de threshold:  1
NO UPDATE

Los valores para la última iteración de la época  3  son:
bias: -0.20
w1:  0.70
w2: 0.90

In [107]:
df_xor = pd.DataFrame(np.array([[0, 0, -1], [0, 1, 1], [1, 0, 1], [1, 1, -1]]),
                   columns=['x1', 'x2', 't'], 
                  index=[1, 2, 3, 4])
df_xor

   x1  x2  t
1   0   0 -1
2   0   1  1
3   1   0  1
4   1   1 -1

In [108]:
w0 = -.8
b = -.8
w1 = 0.5
w2 = 0.5
alpha = 0.2
threshold = 0.4
lab_perceptron(df_xor, w1, w2, alpha, threshold, b)

Época 1 en la iteración 1
net = -0.80 = (0.50 * 0)  + (0.5 * 0) + -0.80
Valor de ynet después de threshold:  -1
NO UPDATE

Época 1 en la iteración 2
net = -0.30 = (0.50 * 0)  + (0.5 * 1) + -0.80
Valor de ynet después de threshold:  -1
w1 = 0.50 = 0.50 + (0.2 * 1 *  0)
w2 = 0.70 = 0.50 + (0.2 * 1 *  1)
b = -0.60 = -0.80 +  (0.2 * 1 * 1)

Época 1 en la iteración 3
net = -0.10 = (0.50 * 1)  + (0.7 * 0) + -0.60
Valor de ynet después de threshold:  -1
w1 = 0.70 = 0.50 + (0.2 * 1 *  1)
w2 = 0.70 = 0.70 + (0.2 * 1 *  0)
b = -0.40 = -0.60 +  (0.2 * 1 * 1)

Época 1 en la iteración 4
net = 1.00 = (0.70 * 1)  + (0.7 * 1) + -0.40
Valor de ynet después de threshold:  1
w1 = 0.50 = 0.70 + (0.2 * -1 *  1)
w2 = 0.50 = 0.70 + (0.2 * -1 *  1)
b = -0.60 = -0.40 +  (0.2 * -1 * 1)

Los valores para la última iteración de la época  1  son:
bias: -0.60
w1:  0.50
w2: 0.50

Época 2 en la iteración 1
net = -0.60 = (0.50 * 0)  + (0.49999999999999994 * 0) + -0.60
Valor de ynet después de threshold:  -1
NO UPDATE

Época 2 en la iteración 2
net = -0.10 = (0.50 * 0)  + (0.49999999999999994 * 1) + -0.60
Valor de ynet después de threshold:  -1
w1 = 0.50 = 0.50 + (0.2 * 1 *  0)
w2 = 0.70 = 0.50 + (0.2 * 1 *  1)
b = -0.40 = -0.60 +  (0.2 * 1 * 1)

Época 2 en la iteración 3
net = 0.10 = (0.50 * 1)  + (0.7 * 0) + -0.40
Valor de ynet después de threshold:  -1
w1 = 0.70 = 0.50 + (0.2 * 1 *  1)
w2 = 0.70 = 0.70 + (0.2 * 1 *  0)
b = -0.20 = -0.40 +  (0.2 * 1 * 1)

Época 2 en la iteración 4
net = 1.20 = (0.70 * 1)  + (0.7 * 1) + -0.20
Valor de ynet después de threshold:  1
w1 = 0.50 = 0.70 + (0.2 * -1 *  1)
w2 = 0.50 = 0.70 + (0.2 * -1 *  1)
b = -0.40 = -0.20 +  (0.2 * -1 * 1)

Los valores para la última iteración de la época  2  son:
bias: -0.40
w1:  0.50
w2: 0.50

Época 3 en la iteración 1
net = -0.40 = (0.50 * 0)  + (0.49999999999999994 * 0) + -0.40
Valor de ynet después de threshold:  -1
NO UPDATE

Época 3 en la iteración 2
net = 0.10 = (0.50 * 0)  + (0.49999999999999994 * 1) + -0.40
Valor de ynet después de threshold:  -1
w1 = 0.50 = 0.50 + (0.2 * 1 *  0)
w2 = 0.70 = 0.50 + (0.2 * 1 *  1)
b = -0.20 = -0.40 +  (0.2 * 1 * 1)

Época 3 en la iteración 3
net = 0.30 = (0.50 * 1)  + (0.7 * 0) + -0.20
Valor de ynet después de threshold:  -1
w1 = 0.70 = 0.50 + (0.2 * 1 *  1)
w2 = 0.70 = 0.70 + (0.2 * 1 *  0)
b = -0.00 = -0.20 +  (0.2 * 1 * 1)

Época 3 en la iteración 4
net = 1.40 = (0.70 * 1)  + (0.7 * 1) + -0.00
Valor de ynet después de threshold:  1
w1 = 0.50 = 0.70 + (0.2 * -1 *  1)
w2 = 0.50 = 0.70 + (0.2 * -1 *  1)
b = -0.20 = -0.00 +  (0.2 * -1 * 1)

Los valores para la última iteración de la época  3  son:
bias: -0.20
w1:  0.50
w2: 0.50